# Use the official Prometheus image
FROM prom/prometheus

# Set the working directory
WORKDIR /etc/prometheus

# Copy the Prometheus configuration file
COPY /prometheus/prometheus.yml /etc/prometheus/prometheus.yml

# Expose the Prometheus port
EXPOSE 9090

# Run Prometheus with the proper configuration file
CMD ["--config.file=/etc/prometheus/prometheus.yml"]
